"""Initial Migration

Revision ID: 822da2cfa9c9
Revises: d879b94ef03a
Create Date: 2019-10-21 19:28:39.573591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '822da2cfa9c9'
down_revision = 'd879b94ef03a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('upvotes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('pitching_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('upvotes')
    # ### end Alembic commands ###
